_commit: v0.4.84
_src_path: git@github.com:tschm/experiments.git
description: A notebook with some advice and a message to Elaine.
gh_create: gh repo create arthrod/welcome-elaine --public --description 'A notebook
  with some advice and a message to Elaine.'
page: https://arthrod.github.io/welcome-elaine
project_name: welcome-elaine
repository: https://github.com/arthrod/welcome-elaine
ssh_uri: git@github.com:arthrod/welcome-elaine.git
status: public
use_dependabot: true
use_devcontainer: true
use_docker: true
use_latex: false
use_renovate: true
username: arthrod
