name: Build and Release

on:
  # Trigger on manual dispatch
  workflow_dispatch

permissions:
  contents: write
  packages: write

jobs:
  tagging:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - name: Generate Tag
        id: tag
        uses: tschm/cradle/actions/tag@v0.1.55
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}


  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: "Build and publish the Container"
        uses: tschm/cradle/actions/docker@v0.1.55
        with:
          github_actor: ${{ github.actor }}
          github_repository: ${{ github.repository }}
          tag: ${{ needs.tagging.outputs.new_tag }}
          github_token: ${{ secrets.github_token }}




  debug:
    runs-on: ubuntu-latest
    needs: tagging
    steps:
      - name: Output
        run: |
          echo "Repository ${{ github.repository }}"
          echo "Tag ${{ needs.tagging.outputs.new_tag }}"
